### PR TITLE
Create Denon-AVR.conf

### PR DESCRIPTION
**Pull request by mad526**
Config for Denon AVR, tested on a Denon AVR 2311

### CODE REVIEW

**Comment by therealmuffin** [comment]
Thanks for the config file. You should be able to enable 2way volume synchronization (unless you use it with e.g. Shairport which doesn't support 2way communication anyway).

This does require the event_delimiter to be set. If you set this to 'V', the volume header to 'M', incoming volume commands are recognized. Obviously this breaks the power on/off commands, but that can (probably) be solved by changing the devicon/deviceoff commands to the following:

`deviceon=("\rPWON");`
`deviceoff=("\rPWSTANDBY");`

Not the prettiest config file, but it should work. 

Let me know if this works or not. If 2way sync. is not of relevance to you or if it doesn't work I'll merge it as

**Comment by mad526** [comment]
just tried it, doesn't seem to work. I'm using MPD by the way. I'm guessing that it doesn't work because the AVR always appends MVMAX 70 (depending on the volume limit set in the AVR menu) on a new line after a volume change? e.g.
MV30
MVMAX 70

also I noticed that the AVR outputs half DB steps in three digits and full DB steps in two, e.g. -45DB results in MV35 while -44.5DB results in MV355. It accepts three digit full DB steps when setting the volume via serial port though, so MV350 does result in -45DB.

**Comment by therealmuffin** [comment]
Ok merged, varying two and three digit volume levels is a problem. I'll see if I can find an elegant solution for that. If I find one, I'll let you know. Thanks for the config file!

**Comment by mad526** [comment]
you're very welcome. thank you for this awesome piece of software.

**Comment by therealmuffin** [comment]
I've added some new functionality and a Denon specific mod. 2way volume synchronization should work now with the update denon-avr.conf config file. If you give it a try, let me know if it works.

**Comment by mad526** [comment]
thanks. With conditional_resize it works, but I had to adjust the scale from 100-600 to 10-60, which means I lost half DB steps. But it's not that big of an issue.

[Denon-AVR.conf.txt](https://github.com/therealmuffin/synchronator/files/154421/Denon-AVR.conf.txt)

**Comment by therealmuffin** [comment]
Ok, that config file is not exactly how I had it in mind but as long as it works I suppose. Thanks for testing, I've updated the config file.

**Pull request merged**
